# Generated by Django 5.1.2 on 2024-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0008_match_info_away_team_possession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_info',
            name='corners_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_info',
            name='corners_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_info',
            name='fouls_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_info',
            name='fouls_home',
            field=models.IntegerField(default=0),
        ),
    ]
